version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - curl -sSL https://install.python-poetry.org | python3 -
      - export PATH="/root/.local/bin:$PATH"
      - poetry --version
      - poetry install

  build:
    commands:
      - poetry run pytest
reports:
  pytest_reports:
    files:
      - './pytest.xml'
    file-format: 'JUNITXML'

